export { default as Head } from './Head';
export { default as About } from './About';
export { default as Experience } from './Experience';
export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Projects } from './Projects';
export { default as Services } from './Services';
export { default as Contact } from './Contact';
export { default as Loader } from './Loader';